<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="ELTAverbaService" targetNamespace="http://tempuri.org/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://tempuri.org/"
                  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
                  xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
                  xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
    <wsdl:types>
        <xsd:schema targetNamespace="http://tempuri.org/Imports">
            <xsd:import schemaLocation="http://www.eltseg.com.br/ELTAverbaService/ELTAverbaService.svc?xsd=xsd1"
                        namespace="http://tempuri.org/"/>
            <xsd:import schemaLocation="http://www.eltseg.com.br/ELTAverbaService/ELTAverbaService.svc?xsd=xsd0"
                        namespace="http://schemas.microsoft.com/Message"/>
            <xsd:import schemaLocation="http://www.eltseg.com.br/ELTAverbaService/ELTAverbaService.svc?xsd=xsd2"
                        namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="RemoteFileInfo">
        <wsdl:part name="parameters" element="tns:RemoteFileInfo"/>
    </wsdl:message>
    <wsdl:message name="RemoteFileInfo_Headers">
        <wsdl:part name="CNPJ" element="tns:CNPJ"/>
        <wsdl:part name="FileName" element="tns:FileName"/>
        <wsdl:part name="Length" element="tns:Length"/>
    </wsdl:message>
    <wsdl:message name="RespostaProcessamento">
        <wsdl:part name="parameters" element="tns:RespostaProcessamento"/>
    </wsdl:message>
    <wsdl:portType name="IELTAverbaService">
        <wsdl:operation name="FileUpload">
            <wsdl:input wsaw:Action="http://tempuri.org/IELTAverbaService/FileUpload" name="RemoteFileInfo"
                        message="tns:RemoteFileInfo"/>
            <wsdl:output wsaw:Action="http://tempuri.org/IELTAverbaService/FileUploadResponse"
                         name="RespostaProcessamento" message="tns:RespostaProcessamento"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="basicHttpBinding12" type="tns:IELTAverbaService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="FileUpload">
            <soap:operation soapAction="http://tempuri.org/IELTAverbaService/FileUpload" style="document"/>
            <wsdl:input name="RemoteFileInfo">
                <soap:header message="tns:RemoteFileInfo_Headers" part="CNPJ" use="literal"/>
                <soap:header message="tns:RemoteFileInfo_Headers" part="FileName" use="literal"/>
                <soap:header message="tns:RemoteFileInfo_Headers" part="Length" use="literal"/>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="RespostaProcessamento">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ELTAverbaService">
        <wsdl:port name="basicHttpBinding12" binding="tns:basicHttpBinding12">
            <soap:address location="http://www.eltseg.com.br/ELTAverbaService/ELTAverbaService.svc"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
